export const authConstants = {
  AUTH_CHANGE_LOGIN_VALUE: "AUTH_CHANGE_LOGIN_VALUE",
  AUTH_CHANGE_PASS_VALUE: "AUTH_CHANGE_PASS_VALUE",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_SET_STATUS: "AUTH_SET_STATUS",
  AUTH_LOGUOT: "AUTH_LOGUOT",
};
